pharo/run.sh

The default test output is not particularly great, partially because Pharo uses CR as line separators, so the output tends to overlap.
However the test runner can produce junit xml artifact... pretty much a universal output across languages and tools.

Running tests now produce junit xml artifacts.

---

run.sh

In 5c16ba63b092de2f0debca406644be426a678557 the loadSpecs got
renamed to loading but the default file generation has not been
updated.

Fix the default config by using 'loading' and not 'loadSpecs'

---

gemstone/run.sh

GsDevKit/GsDevKit_home#75 has been merged, so time to switch to master branch. Note that Issue #54 is intended to address the general problem ... editing the run.sh is not a proper solution

Issue #72: switch back to using master branch of GsDevKit_home

---

gemstone/run.sh
run.sh

- Remove the --gs-* args that don't apply quite yet
- Partial fix for Issue #102 - fix typos for the `--clean` messages
- changes needed to make the `--gs-*` args code fuctional ...
- fix a GemStone-only bug in `--clear`

Infrastructure for GemStone-specific eun.sh args

---

gemstone/run.sh

Adding support to GsDevKit_home for Pharo-6.0, so will need to update the gemstone/run.sh script to permit pharo6.0 clients

expand gemstone client support to include pharo6.0

---

README.md

The anchor has to be inside the heading, otherwise it breaks the output

Fixed headings and anchors.

---

pharo/run.sh
tests/pharo_tests.sh

Apparently this was also requested in https://github.com/hpi-swa/smalltalkCI/issues/274 (274 however also requests 64bit and threaded heartbeat, which this PR doesn't address)

Pharo-alpha should also use the latest VM, not just the latest image

---

README.md

Fix linking of SmalltalkCISpec chapter - links must be in the same line

Fix linking in readme

---

pharo/run.sh

Pharo users can have special preferences that run on image startup. This introduces unexpected issues when trying to reproduce Smalltalk-CI behavior locally.

Run Pharo images without default preferences

---

.travis.yml
README.md
pharo/run.sh
run.sh

I added a support for Pharo 64 bit images/vms as requested in the issue #286
Now I think that maybe it makes more sense to have one more matrix axis fir 32/64 architectures? Squeak seems to be experimenting with 64 bit so probably they will release a stable version in a near future too. And Pharo 64 bit scripts mostly mirror the 32 bit ones

Added 64 bit support

---

repository/SmalltalkCI-Core.package/SCITestRunner.class/instance/tearDown.st

Besides the issue fixed in the commit there is another, maybe larger, one. When I ran a job with zero tests it initially failed which confused me as I always read the example configuration in the Readme.md as the standard configuration and so I was expecting the flag to be set to false and the build to not fail. Maybe we should add a sentence before the example configuration illustrating that these are merely some example values.

failOnZeroTests mixup

---

.travis.yml
repository/SmalltalkCI-Pharo-Tests.package/SCIPharoCodeCoverageTest.class/instance/testMethodReferenceForSelector.st
repository/SmalltalkCI-Pharo-Tests.package/SCIPharoCodeCoverageTest.class/methodProperties.json
repository/SmalltalkCI-Pharo-Tests.package/monticello.meta/version

Update test to use the same methods than in the the code to test
Fixes https://github.com/hpi-swa/smalltalkCI/issues/434

434-SCIPharoCodeCoverageTesttestMethodReferenceForSelector-fails-on-Pharo-8

---

.travis.yml
README.md
pharo/run.sh
repository/BaselineOfSmalltalkCI.package/BaselineOfSmalltalkCI.class/instance/setUpPharo5AndGreaterPackages..st
repository/SmalltalkCI-Pharo-Core.package/SmalltalkCIPharo78.class/class/isPlatformCompatible.st
run.sh
tests/pharo_tests.sh

We are getting ready to the release of Pharo8, and Pharo9 development has already started

Adding Pharo9 as a valid version

---

README.md

Build metrics are collected as well when running smalltalkCI another CI platform, e.g. GitHub Actions. Generalize the description so that no one can complain. :-)

Refine description of build metrics collection

---

run.sh

For more information on this bug see: https://unix.stackexchange.com/a/513498/448260

Fix handling of CTRL + C during smalltalk image prompt

---

helpers.sh

Fixes #516. Note that in case of a connection error such as 404, this timeout would not be relevant but we would receive an immediate error instead.

download_file(): Raise timeouts

---

run.sh

`run.sh`: In `main()`, invert the invocation order of `check_clean_up` and 
`ensure_ston_config_exists`, to prevent error messages regarding the absence of configuration when the command was invoked to clean up the cache only. Resolve the existing dependency order which was manifested by the 
`config_smalltalk` variable (read in `check_clean_up` and written in `ensure_ston_config_exists`) by moving the "Continue with build progress?" prompt into the latter function, `ensure_ston_config_exists`. We only show this prompt if the local variable 
`first_action` has been set, which at the moment only happens in `check_clean_up`.
Fixes #519.

CLI: Fix --clean option if configuration is absent

---

README.md

My Fuel builds on AppVeyor have been failing because I was using the wrong architecture. I had not realized that Cygwin must be bootstrapped to 64-bits.
I have updated the appveyor.yaml example in the README.md to use 64-bit Cygwin, as the images in that example are 64-bit anyway.

Updated appveyor.yaml example in README.md to use 64-bit Cygwin

---

pharo/run.sh

This pull request fixes a bug in ‘pharo::prepare_image’ where the image was always downloaded again due to ‘is_file’ being used instead of ‘is_dir’ to test the existence of the ‘target’ directory.
The bug seems to have been introduced in commit 3018a631f2a5839d, [the test](https://github.com/hpi-swa/smalltalkCI/commit/3018a631f2a5839dbb465df7ceebd5b32c1c384b#diff-7f52e0a9b563ce4153613b54b061993866eae81210e41e93a4c81362d31f29b7L189-R187) previously checked the existence of the image file instead of the directory.

Fix bug in ‘pharo::prepare_image’ which always downloads the image again

---

pharo/run.sh

This PR aims to fix the URL of Moose10 to target the Moose stable version of Moose10.
@ClotildeToullec  should be able to review I did not miss something 😃

Update the URL to Moose10 stable version

---

repository/SmalltalkCI-Pharo-Core.package/SmalltalkCIPharo12.class/class/allCategoryNames.st
repository/SmalltalkCI-Pharo-Core.package/SmalltalkCIPharo12.class/class/setAuthor..st
repository/SmalltalkCI-Tests.package/SmalltalkCITest.class/instance/testAuthor.st

This PR introduces two small changes to use updated versions of deprecated methods in Pharo 12, avoiding Debugger windows when running in interactive mode.
- Use `tags` instead of `classTags` (deprecated in Pharo12)
- Use `Author fullName:`  instead of `setAuthor` (deprecated in Pharo12).
- Changes in .json files are just a re-ordering of properties.

Updates for Pharo12 deprecated methods.

---

helpers.sh

In order to use `git` commands for generating the Coveralls report, the script needs to `cd` to `SMALLTALK_CI_HOME` first.
Fixes #626

fix: change directory for Coveralls report

---

gtoolkit/run.sh
helpers.sh
pharo/run.sh
run.sh
squeak/run.sh

- new option to force download of an image and override the cache
- never use the cached image for in-development versions (*-trunk | *-alpha)

feat: always update development images

---

repository/SmalltalkCI-Pharo-Core.package/SmalltalkCIPharo11.class/class/saveImage.st
repository/SmalltalkCI-Pharo-Core.package/SmalltalkCIPharo11.class/methodProperties.json
repository/SmalltalkCI-Pharo-Core.package/SmalltalkCIPharo12.class/methodProperties.json

adjusted saveImage for Pharo11 as it returns a SnapshotOperation instead

---

.github/workflows/main.yml

Fix for issue #613. Versions older than GemStone 3.7.1 will not run on macos-latest (14.x), adjust the lineup with expected failures and add 3.7.1.
My [CI run failed](https://github.com/dalehenrich/smalltalkCI/actions/runs/9045789613), however the failure was a [Squeak32-4.5 job timing out](https://github.com/dalehenrich/smalltalkCI/actions/runs/9045789613/job/24855908626) so I don't think my changes impacted the Squeak32 job.

Update lineup for GemStone and fix Issue #613

---

gtoolkit/run.sh

Errors like the following were happening because the folder was being passed to curl instead of the file: Starting GToolkit build...
Downloading GToolkit64-release image...
curl: (23) Failure writing output to destination
curl failed to download https://github.com/feenkcom/gtoolkit/releases/download/v1.0.773/GlamorousToolkit-MacOS-aarch64-v1.0.773.zip to '~/Repositories/smalltalkCI/_cache/GlamorousToolkit-MacOS-aarch64-v1.0.773.zip'.

[Bug]: GToolkit Download Target Should Include Zip Extension

---

helpers.sh
repository/SmalltalkCI-Pharo-Core.package/SmalltalkCIPharo11.class/class/newTravisID.st
repository/SmalltalkCI-Pharo-Core.package/SmalltalkCIPharo13.class/instance/imageInfo.st
repository/SmalltalkCI-Pharo-Core.package/SmalltalkCIPharo13.class/methodProperties.json

`StSystemReporter` was removed in Pharo 13.

feat: report image info without `StSystemReporter`

---

pharo/run.sh

Moose images are now in a zipped directory. The `-j` flag ensures that only the files are unzipped.

Moose image extraction: add a flag to unzip only files

---

helpers.sh

The environment variable has been rename on GitLab. Deprecated in version 9.x and removed now.
I think we can replace them in the script now.
It creates bugs 
see https://github.com/fsprojects/FAKE/issues/2290#issuecomment-522197031

Rename env variable for GitLab build

---

.github/workflows/main.yml

Ubuntu 20.04 has been deprecated

chore: update Linux runner on GitHub

---

.github/workflows/main.yml
README.md
pharo/run.sh
run.sh

Moose 12 has been released as stable.
Moose 13 is the dev version. It runs on Pharo 13.

Add Moose 13
