README.md, pharo/run.sh
... but I cannot tests it. 
I hope it works :)
=> changed to resemble more a pharo build process

.travis.yml, helpers.sh, pharo/run.sh, run.sh, squeak/load.st, squeak/load_baseline.st, squeak/load_configuration.st, squeak/run.sh, squeak/run.st
This PR includes some improvements and resolves some issues.
=> smalltalkCI Updates

pharo/run.sh
=> Persist changes to the image for Pharo.

helpers.sh
=> add new line before ending travis fold after jUnit XML output

README.md
=> [ci skip] Added @marianopeck projects using smalltalk-ci

README.md, gemstone/run.sh, helpers.sh, pharo/run.sh, squeak/run.sh
Closes #154.
/cc @Uko @dalehenrich
=> Add the ability to increase timeout for jobs with no output for 10mins

README.md, helpers.sh, run.sh
and add --no-tracking option (#220)
=> Don't track private repositories

README.md
=> Added RenoirSt to projects using smalltalkCI

.travis.yml, gemstone/run.sh, pharo/run.sh
with PR #311 stalled, add just the basic support
=> add support for Pharo-6.1

README.md, gemstone/run.sh, helpers.sh, pharo/run.sh, run.sh, squeak/run.sh
=> Fix for issue #321

pharo/run.sh
=> Load correct Pharo6.1 vm and image

.appveyor.yml, .travis.yml, README.md, run.sh, squeak/run.sh
This should fix #400 once the corresponding release has been made (assumed to be 2.8.3).
=> Add squeak 5.2

.travis.yml, README.md, pharo/run.sh, run.sh, tests/pharo_tests.sh
Add Pharo 8 support. Mark Pharo 7 as the stable version.
Fixes #409
=> Add Pharo 8

.travis.yml, README.md, pharo/run.sh, run.sh
Hi,
I've tried to change the files to add Moose 7.0
It's the first time i'm doing something like this, so it needs a real review.
=> Add Moose 7.0

.travis.yml, README.md, pharo/run.sh, run.sh
I tried to add Moose 8.0 and the 64bits version of Moose 7 and 8
=> Add Moose 8.0 and Moose 64bit

.travis.yml, README.md, pharo/run.sh
Moose 32 8.0 doesn't exist
The url for Moose 8 does not follow the same format
=> Update Moose CI

run.sh
=> When smalltalk_config is a ruby array string, extract the first value

README.md, gemstone/README.md
For easier asset management, we will use asset issue #467 in future.
This will allow users to easily upload assets for their own PRs.
=> Use asset-issue instead of assets branch

.github/workflows/main.yml, README.md, pharo/run.sh, run.sh
This PR aims to add the support of Moose-9.0 (the version under dev)
=> Add Moose-9.0

pharo/run.sh
This method doesn't exist in the Metacello versions loaded into Pharo 3 and 4. Instead, we can use #onConflict: directly
=> Before using Metacello>>onConflictUseIncoming, check if its there.

.github/workflows/main.yml, README.md, pharo/run.sh, run.sh
- Added Moose 10 to available Moose versions
- Updated Moose 9 and Moose 8 urls
=> Add Moose 10

repository/BaselineOfSmalltalkCI.package/BaselineOfSmalltalkCI.class/instance/setUpPharo5AndGreaterPackages..st
baseline is not working for pharo10
=> add pharo10

run.sh
=> Add Pharo 10 and 11 to image selection list

.github/workflows/main.yml
Make it possible to trigger the CI manually from the Actions page.
=> Add `workflow_dispatch` trigger to CI

.github/workflows/main.yml, README.md, pharo/run.sh, repository/BaselineOfSmalltalkCI.package/BaselineOfSmalltalkCI.class/instance/setUpPharo5AndGreaterPackages..st, repository/SmalltalkCI-Pharo-Core.package/SmalltalkCIPharo12.class/class/isPlatformCompatible.st, repository/SmalltalkCI-Pharo-Core.package/SmalltalkCIPharo12.class/methodProperties.json, repository/SmalltalkCI-Pharo-Core.package/SmalltalkCIPharo12.class/properties.json, repository/SmalltalkCI-Pharo-Coverage-Core.package/SCIPharoCodeCoverage.class/class/packageNameForMethod..st, run.sh
This PR enable Pharo 12 in smalltalk CI
=> Enable Pharo 12

.github/workflows/main.yml, README.md, pharo/run.sh
Hello
This PR aims to add the build with Moose11.
=> Add Moose 11

helpers.sh
=> fix: get coveralls data from correct directory

README.md, pharo/run.sh, run.sh
Removing references to old versions of Moose that are no longer available.
=> Remove unsupported Moose images

.github/workflows/main.yml, README.md, pharo/run.sh, repository/BaselineOfSmalltalkCI.package/BaselineOfSmalltalkCI.class/instance/setUpPharo5AndGreaterPackages..st, repository/SmalltalkCI-Pharo-Core.package/SmalltalkCIPharo13.class/class/isPlatformCompatible.st, repository/SmalltalkCI-Pharo-Core.package/SmalltalkCIPharo14.class/class/isPlatformCompatible.st, repository/SmalltalkCI-Pharo-Core.package/SmalltalkCIPharo14.class/properties.json
now yes, let's see how it goes :)
=> add Pharo14
